# Based on libgit2/include/common.h
#
# This file should be sourced into whatever namespace commands should
# be created in.

::cffi::enum flags git_feature_t {
    GIT_FEATURE_THREADS
    GIT_FEATURE_HTTPS
    GIT_FEATURE_SSH
    GIT_FEATURE_NSEC
}

libgit2 functions {
    git_libgit2_version GIT_ERROR_CODE {major {int out} minor {int out} rev {int out}}
    git_libgit2_features {int {enum git_feature_t} bitmask} {}
}

::cffi::enum sequence git_libgit2_opt_t {
    GIT_OPT_GET_MWINDOW_SIZE
    GIT_OPT_SET_MWINDOW_SIZE
    GIT_OPT_GET_MWINDOW_MAPPED_LIMIT
    GIT_OPT_SET_MWINDOW_MAPPED_LIMIT
    GIT_OPT_GET_SEARCH_PATH
    GIT_OPT_SET_SEARCH_PATH
    GIT_OPT_SET_CACHE_OBJECT_LIMIT
    GIT_OPT_SET_CACHE_MAX_SIZE
    GIT_OPT_ENABLE_CACHING
    GIT_OPT_GET_CACHED_MEMORY
    GIT_OPT_GET_TEMPLATE_PATH
    GIT_OPT_SET_TEMPLATE_PATH
    GIT_OPT_SET_SSL_CERT_LOCATIONS
    GIT_OPT_SET_USER_AGENT
    GIT_OPT_ENABLE_STRICT_OBJECT_CREATION
    GIT_OPT_ENABLE_STRICT_SYMBOLIC_REF_CREATION
    GIT_OPT_SET_SSL_CIPHERS
    GIT_OPT_GET_USER_AGENT
    GIT_OPT_ENABLE_OFS_DELTA
    GIT_OPT_ENABLE_FSYNC_GITDIR
    GIT_OPT_GET_WINDOWS_SHAREMODE
    GIT_OPT_SET_WINDOWS_SHAREMODE
    GIT_OPT_ENABLE_STRICT_HASH_VERIFICATION
    GIT_OPT_SET_ALLOCATOR
    GIT_OPT_ENABLE_UNSAVED_INDEX_SAFETY
    GIT_OPT_GET_PACK_MAX_OBJECTS
    GIT_OPT_SET_PACK_MAX_OBJECTS
    GIT_OPT_DISABLE_PACK_KEEP_FILE_CHECKS
    GIT_OPT_ENABLE_HTTP_EXPECT_CONTINUE
    GIT_OPT_GET_MWINDOW_FILE_LIMIT
    GIT_OPT_SET_MWINDOW_FILE_LIMIT
    GIT_OPT_SET_ODB_PACKED_PRIORITY
    GIT_OPT_SET_ODB_LOOSE_PRIORITY
    GIT_OPT_GET_EXTENSIONS
    GIT_OPT_SET_EXTENSIONS
}

# TODO - needs varargs support
# GIT_EXTERN(int) git_libgit2_opts(int option, ...);

