name: mac

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:

    - name: Checkout tcl-cffi
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Tcl and libffi
      run: |
        brew update
        brew install tcl-tk libffi ossp-uuid || true

    - name: Install dyncall
      run: |
        wget https://dyncall.org/r1.4/dyncall-1.4.tar.gz
        tar xf dyncall-1.4.tar.gz
        cd dyncall-1.4
        mkdir build
        cd build
        ../configure --prefix=$GITHUB_WORKSPACE/external-libs/macos
        make
        make install

    - name: Configure with dyncall
      run: |
        mkdir build-dyncall
        cd build-dyncall
        ../configure --with-tcl=/usr/local/opt/tcl-tk/lib LDFLAGS=-L$GITHUB_WORKSPACE/external-libs/macos/lib CPPFLAGS=-I$GITHUB_WORKSPACE/external-libs/macos/include --with-dyncall

    - name: Make with dyncall
      run: |
        cd build-dyncall
        make

    - name: Test with dyncall
      run: |
        cd build-dyncall
        make test
      env:
        ERROR_ON_FAILURES: 1

    - name: Configure with libffi
      run: |
        mkdir build-libffi
        cd build-libffi
        ../configure --with-tcl=/usr/local/opt/tcl-tk/lib LDFLAGS="-L/usr/local/opt/libffi/lib" CFLAGS="-I/usr/local/opt/libffi/include" --disable-staticffi

    - name: Make with libffi
      run: |
        cd build-libffi
        make

    - name: Test with libffi
      run: |
        cd build-libffi
        make test
      env:
        ERROR_ON_FAILURES: 1

