name: Mingw

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - {tclbranch: main, arch: mingw64, cpu: x86_64}
          - {tclbranch: main, arch: mingw32, cpu: i686}
          - {tclbranch: core-8-6-13, arch: mingw64, cpu: x86_64}
          - {tclbranch: core-8-6-13, arch: mingw32, cpu: i686}
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout tcl-cffi
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.arch }}
        path-type: minimal
        release: true
        update: false
        install: mingw-w64-${{matrix.cpu}}-gcc make

    - name: Verify toolchain
      run: |
        gcc -v
        make -v

    - name: Setup Tcl
      id: setup-tcl-step
      uses: apnadkarni/setup-tcl@main
      with:
        tcl-osver: ${{ matrix.os }}
        tcl-branch: ${{ matrix.tclbranch }}
        tcl-toolchain: 'mingw64'
        tcl-arch: ${{ matrix.arch }}

    - name: Cache dyncall
      id: dyncall-cache
      uses: actions/cache@v4
      with:
        path: C:/dyncall
        key: ${{ runner.os }}-dyncall-${{ matrix.arch }}

    - name: Install dyncall
      if: steps.dyncall-cache.outputs.cache-hit != 'true'
      run: |
        wget https://dyncall.org/r1.4/dyncall-1.4.tar.gz
        tar xf dyncall-1.4.tar.gz
        cd dyncall-1.4
        mkdir build
        cd build
        ../configure --prefix=/c/dyncall
        make
        make install

    - name: Install libffi
      run: |
        pacman --sync --refresh --needed --noconfirm  ${MINGW_PACKAGE_PREFIX}-libffi

    - name: Configure with dyncall
      run: |
        mkdir build-dyncall
        cd build-dyncall
        ../configure --with-tcl=${{ env.TCLDIR }}/lib --with-tclinclude=${{ env.TCLDIR }}/include LDFLAGS=-L/c/dyncall/lib CPPFLAGS=-I/c/dyncall/include --with-dyncall

    - name: Make with dyncall
      run: |
        cd build-dyncall
        make

    - name: Test with dyncall
      run: |
        cd build-dyncall
        make test
      env:
        ERROR_ON_FAILURES: 1

    - name: Configure with libffi
      run: |
        mkdir build-libffi
        cd build-libffi
        ../configure --with-tcl=${{ env.TCLDIR }}/lib --with-tclinclude=${{ env.TCLDIR }}/include

    - name: Make with libffi
      run: |
        cd build-libffi
        make

    - name: Test with libffi
      run: |
        cd build-libffi
        make test
      env:
        ERROR_ON_FAILURES: 1
