name: Ubuntu

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout tcl-cffi  
      uses: actions/checkout@v2

    - name: Install Tcl
      run: |
        sudo apt-get install -y tcl8.6-dev

    - name: Install dyncall
      run: |
        wget https://dyncall.org/r1.2/dyncall-1.2.tar.gz
        tar xf dyncall-1.2.tar.gz
        cd dyncall-1.2
        mkdir build
        cd build
        ../configure --prefix=$GITHUB_WORKSPACE/external-libs/ubuntu/x64
        make
        make install

    - name: Configure
      run: |
        mkdir build
        cd build
        ../configure --with-tcl=/usr/lib/tcl8.6 --enable-64bit LDFLAGS=-L$GITHUB_WORKSPACE/external-libs/ubuntu/x64/lib CPPFLAGS=-I$GITHUB_WORKSPACE/external-libs/ubuntu/x64/include

    - name: Make
      run: |
        cd build
        make
        make test

