name: C/C++ CI

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install -y tcl8.6-dev
    - name: Configure
      run: ./configure --with-tcl=/usr/lib/tcl8.6
    - name: make
      run: make
    - name: Test
      run: make test
