name: Ubuntu

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout tcl-cffi  
      uses: actions/checkout@v2
      with:
        path: tcl-cffi

    - name: Install Tcl
      run: |
        sudo apt-get install -y tcl8.6-dev

    - name: Install dyncall
      run: |
        wget https://dyncall.org/r1.2/dyncall-1.2.tar.gz
        tar xf dyncall-1.2.tar.gz
        cd dyncall-1.2
        mkdir build
        cd build
        ../configure --prefix=~/tcl-cffi/external-libs/ubuntu/x64
        make
        make install

    - name: Configure
      run: |
        cd tcl-cffi
        mkdir build
        cd build
        ./configure --with-tcl=/usr/lib/tcl8.6 --enable-64bit LDFLAGS=-L~/tcl-cffi/external-libs/ubuntu/x64/lib CPPFLAGS=-I~/tcl-cffi/external-libs/ubuntu/x64/include

    - name: Make
      working-directory: tcl-cffi/build
      run: make

    - name: Test
      working-directory: tcl-cffi/build
      run: make test
